# Generated by Django 6.0 on 2025-12-31 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('READING', '독해'), ('SYNTAX', '구문')], max_length=20)),
                ('chapter', models.IntegerField()),
                ('number', models.IntegerField()),
                ('image', models.ImageField(upload_to='questions/')),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to='answers/')),
                ('style', models.CharField(choices=[('CONCEPT', '지문'), ('ANALYSIS', '구문/분석')], default='CONCEPT', max_length=20)),
                ('reading_type', models.CharField(blank=True, max_length=20, null=True)),
                ('question_text', models.TextField(blank=True, verbose_name='지문 텍스트(검색용)')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.textbook')),
            ],
        ),
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_chapters', models.CharField(blank=True, max_length=100)),
                ('questions', models.ManyToManyField(to='exam.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_papers', to='core.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='점수')),
                ('date', models.DateField(auto_now_add=True, verbose_name='응시일')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='채점 상세')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='core.studentprofile', verbose_name='학생')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exam.testpaper')),
            ],
            options={
                'verbose_name': '월말평가 결과 데이터',
                'verbose_name_plural': '월말평가 결과 데이터',
            },
        ),
    ]
