# Generated by Django 6.0 on 2026-01-01 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_studentprofile_base_year'),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionUpload',
            fields=[
            ],
            options={
                'verbose_name': '📸 문제 대량 업로드',
                'verbose_name_plural': '📸 문제 대량 업로드',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('exam.question',),
        ),
        migrations.AlterModelOptions(
            name='examresult',
            options={'verbose_name': '월말평가 결과', 'verbose_name_plural': '월말평가 결과'},
        ),
        migrations.AlterField(
            model_name='examresult',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='core.studentprofile'),
        ),
        migrations.CreateModel(
            name='ExamResultDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.CharField(blank=True, max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_set', to='exam.examresult')),
            ],
        ),
    ]
