# Generated by Django 6.0 on 2025-12-31 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='지점명')),
            ],
            options={
                'verbose_name': '지점(캠퍼스)',
                'verbose_name_plural': '지점(캠퍼스)',
            },
        ),
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='수업명 (예: 구문_평일)')),
                ('day', models.CharField(choices=[('Mon', '월요일'), ('Tue', '화요일'), ('Wed', '수요일'), ('Thu', '목요일'), ('Fri', '금요일'), ('Sat', '토요일'), ('Sun', '일요일')], max_length=3, verbose_name='요일')),
                ('start_time', models.TimeField(verbose_name='시작 시간')),
                ('end_time', models.TimeField(verbose_name='종료 시간')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.branch', verbose_name='지점')),
            ],
            options={
                'verbose_name': '수업 시간표',
                'verbose_name_plural': '수업 시간표',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='학교명')),
                ('region', models.CharField(blank=True, max_length=30, verbose_name='지역')),
                ('branches', models.ManyToManyField(blank=True, related_name='schools', to='core.branch', verbose_name='관련 지점')),
            ],
            options={
                'verbose_name': '학교',
                'verbose_name_plural': '학교',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='선생님 성함')),
                ('position', models.CharField(choices=[('TEACHER', '일반 강사'), ('VICE', '부원장'), ('PRINCIPAL', '원장')], default='TEACHER', max_length=10, verbose_name='직책')),
                ('is_syntax_teacher', models.BooleanField(default=False, verbose_name='구문 수업 가능')),
                ('is_reading_teacher', models.BooleanField(default=False, verbose_name='독해 수업 가능')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='소속 지점')),
                ('managed_teachers', models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, related_name='managers', to=settings.AUTH_USER_MODEL, verbose_name='[부원장용] 담당 강사 선택')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='학생 이름')),
                ('base_year', models.IntegerField(default=2025, verbose_name='기준 연도')),
                ('base_grade', models.IntegerField(choices=[(1, '초1'), (2, '초2'), (3, '초3'), (4, '초4'), (5, '초5'), (6, '초6'), (7, '중1'), (8, '중2'), (9, '중3'), (10, '고1'), (11, '고2'), (12, '고3'), (13, '졸업/성인')], default=7, verbose_name='기준 학년')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='주소')),
                ('attendance_code', models.CharField(blank=True, max_length=4, null=True, verbose_name='출석 코드')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('parent_phone_mom', models.CharField(blank=True, max_length=15, null=True, verbose_name='어머님 연락처')),
                ('parent_phone_dad', models.CharField(blank=True, max_length=15, null=True, verbose_name='아버님 연락처')),
                ('extra_class_type', models.CharField(blank=True, choices=[('SYNTAX', '구문'), ('READING', '독해')], max_length=10, null=True, verbose_name='추가 수업 종류')),
                ('memo', models.TextField(blank=True, verbose_name='특이사항 메모')),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('last_wrong_failed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='소속 지점')),
                ('extra_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_extra', to='core.classtime', verbose_name='추가 수업 시간')),
                ('extra_class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_students', to=settings.AUTH_USER_MODEL, verbose_name='추가 수업 담당 선생님')),
                ('reading_class', models.ForeignKey(blank=True, limit_choices_to={'name__contains': '독해'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_reading', to='core.classtime', verbose_name='독해 시간표')),
                ('reading_teacher', models.ForeignKey(blank=True, limit_choices_to={'staff_profile__is_reading_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_students', to=settings.AUTH_USER_MODEL, verbose_name='독해 담당 선생님')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.school', verbose_name='학교')),
                ('syntax_class', models.ForeignKey(blank=True, limit_choices_to={'name__contains': '구문'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_syntax', to='core.classtime', verbose_name='구문 시간표')),
                ('syntax_teacher', models.ForeignKey(blank=True, limit_choices_to={'staff_profile__is_syntax_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syntax_students', to=settings.AUTH_USER_MODEL, verbose_name='구문 담당 선생님')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '학생 프로필',
                'verbose_name_plural': '학생 프로필',
            },
        ),
    ]
