# Generated by Django 6.0 on 2026-01-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='base_year',
            field=models.IntegerField(default=2026, verbose_name='기준 연도'),
        ),
    ]
