# Generated by Django 6.0 on 2026-01-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_studentprofile_base_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='attendance_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='출석 코드'),
        ),
    ]
