# Generated by Django 6.0 on 2026-01-07 17:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studentprofile_notification_recipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='팝업 제목')),
                ('image', models.ImageField(blank=True, null=True, upload_to='popups/', verbose_name='팝업 이미지')),
                ('content', models.TextField(blank=True, verbose_name='팝업 텍스트 내용')),
                ('link', models.URLField(blank=True, null=True, verbose_name='클릭 시 이동할 주소')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='게시 시작일')),
                ('end_date', models.DateTimeField(verbose_name='게시 종료일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popups', to='core.branch', verbose_name='소속 지점')),
            ],
            options={
                'verbose_name': '메인 팝업 관리',
                'verbose_name_plural': '메인 팝업 관리',
            },
        ),
    ]
