# Generated by Django 6.0 on 2025-12-31 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='출판사명')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=100)),
                ('test_range', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_results', to='core.studentprofile')),
            ],
            options={
                'verbose_name': '월말평가 결과',
                'verbose_name_plural': '월말평가 결과',
            },
        ),
        migrations.CreateModel(
            name='MonthlyTestResultDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_question', models.CharField(max_length=100)),
                ('student_answer', models.CharField(max_length=100)),
                ('correct_answer', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('is_correction_requested', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='vocab.monthlytestresult')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='점수')),
                ('total_count', models.IntegerField(default=30)),
                ('wrong_count', models.IntegerField(default=0)),
                ('test_range', models.CharField(blank=True, max_length=50, verbose_name='시험 범위')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='응시 일시')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='core.studentprofile', verbose_name='학생')),
            ],
            options={
                'verbose_name': '도전모드 결과',
                'verbose_name_plural': '도전모드 결과',
            },
        ),
        migrations.CreateModel(
            name='TestResultDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_question', models.CharField(max_length=100)),
                ('student_answer', models.CharField(max_length=100)),
                ('correct_answer', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('is_correction_requested', models.BooleanField(default=False, verbose_name='정답 정정 요청')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='처리 완료')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='vocab.testresult')),
            ],
        ),
        migrations.CreateModel(
            name='WordBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='단어장 제목')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='csvs/', verbose_name='CSV 파일')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocab.publisher', verbose_name='출판사')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '단어장',
                'verbose_name_plural': '단어장',
            },
        ),
        migrations.AddField(
            model_name='testresult',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.wordbook', verbose_name='시험 본 책'),
        ),
        migrations.AddField(
            model_name='monthlytestresult',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.wordbook'),
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='Day/Unit')),
                ('english', models.CharField(max_length=100)),
                ('korean', models.CharField(max_length=100)),
                ('example_sentence', models.TextField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='vocab.wordbook')),
            ],
            options={
                'ordering': ['number', 'id'],
                'unique_together': {('book', 'english')},
            },
        ),
    ]
