# Generated by Django 6.0 on 2026-01-03 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_studentprofile_attendance_code'),
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalWrongWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_wrong_words', to='core.studentprofile')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.word')),
            ],
            options={
                'verbose_name': '학생 추가 오답',
                'verbose_name_plural': '학생 추가 오답',
                'unique_together': {('student', 'word')},
            },
        ),
    ]
