# Generated by Django 6.0 on 2026-01-06 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_personalwrongword'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='예: 🌞 여름방학 능률보카 격파왕', max_length=100, verbose_name='이벤트 타이틀')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('is_active', models.BooleanField(default=True, verbose_name='현재 진행 중')),
                ('target_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.wordbook', verbose_name='이벤트 대상 단어장')),
            ],
            options={
                'verbose_name': '🏆 랭킹 이벤트 설정',
                'verbose_name_plural': '🏆 랭킹 이벤트 설정',
            },
        ),
    ]
