# Generated by Django 6.0 on 2025-12-31 21:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2025, verbose_name='연도')),
                ('month', models.IntegerField(default=12, verbose_name='월')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_days', models.IntegerField(default=0, verbose_name='총 수업 일수')),
                ('present_days', models.IntegerField(default=0, verbose_name='출석 횟수')),
                ('late_days', models.IntegerField(default=0, verbose_name='지각 횟수')),
                ('absent_days', models.IntegerField(default=0, verbose_name='결석 횟수')),
                ('makeup_count', models.IntegerField(default=0, verbose_name='보강 횟수')),
                ('unexcused_absent', models.IntegerField(default=0, verbose_name='무단 결석')),
                ('vocab_progress_info', models.CharField(blank=True, max_length=100, verbose_name='단어장 진행 현황')),
                ('vocab_test_count', models.IntegerField(default=0, verbose_name='총 응시 횟수')),
                ('vocab_pass_count', models.IntegerField(default=0, verbose_name='Pass 횟수')),
                ('vocab_fail_count', models.IntegerField(default=0, verbose_name='Fail 횟수')),
                ('vocab_average_score', models.FloatField(default=0.0, verbose_name='단어 시험 평균 점수')),
                ('study_summary', models.TextField(blank=True, verbose_name='수업 진행 내용 요약')),
                ('textbook_progress', models.CharField(blank=True, max_length=200, verbose_name='교재 진행 상황')),
                ('performance_comment', models.TextField(blank=True, verbose_name='수업 수행도 코멘트')),
                ('exam_score_vocab', models.IntegerField(default=0, verbose_name='[월말] 어휘 점수')),
                ('exam_score_syntax', models.IntegerField(default=0, verbose_name='[월말] 구문 점수')),
                ('exam_score_reading', models.IntegerField(default=0, verbose_name='[월말] 독해 점수')),
                ('exam_score_listening', models.IntegerField(default=0, verbose_name='[월말] 듣기 점수')),
                ('class_average_score', models.FloatField(default=0.0, verbose_name='반 평균')),
                ('overall_comment', models.TextField(blank=True, verbose_name='선생님 총평')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.studentprofile', verbose_name='학생')),
            ],
            options={
                'verbose_name': '월간 성적표',
                'verbose_name_plural': '월간 성적표',
                'unique_together': {('student', 'year', 'month')},
            },
        ),
    ]
