# Generated by Django 6.0 on 2026-01-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreport',
            name='month',
            field=models.IntegerField(default=1, verbose_name='월'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='year',
            field=models.IntegerField(default=2026, verbose_name='연도'),
        ),
    ]
