# Generated by Django 6.0 on 2026-01-02 14:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_studentprofile_base_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(default=django.utils.timezone.now, verbose_name='시행일')),
                ('title', models.CharField(help_text='예: 3월 1주차 모의고사, 2024 고1 3월 학평 등', max_length=50, verbose_name='시험명')),
                ('score', models.IntegerField(verbose_name='원점수')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='등급')),
                ('wrong_listening', models.IntegerField(default=0, verbose_name='듣기 오답 수')),
                ('wrong_vocab', models.IntegerField(default=0, verbose_name='어휘 오답 수')),
                ('wrong_grammar', models.IntegerField(default=0, verbose_name='어법 오답 수')),
                ('wrong_reading', models.IntegerField(default=0, verbose_name='독해 오답 수')),
                ('note', models.TextField(blank=True, verbose_name='비고/피드백')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='입력한 선생님')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_exams', to='core.studentprofile', verbose_name='학생')),
            ],
            options={
                'verbose_name': '모의고사 성적',
                'verbose_name_plural': '모의고사 성적',
                'ordering': ['-exam_date'],
            },
        ),
    ]
