# Generated by Django 6.0 on 2026-01-02 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockExamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='시험명')),
                ('year', models.IntegerField(default=2026, verbose_name='연도')),
                ('month', models.IntegerField(verbose_name='월')),
                ('grade', models.IntegerField(choices=[(1, '고1'), (2, '고2'), (3, '고3')], verbose_name='대상 학년')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '모의고사 정답지(회차)',
                'verbose_name_plural': '모의고사 정답지(회차)',
                'ordering': ['-year', '-month', 'grade'],
            },
        ),
        migrations.CreateModel(
            name='MockExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='문항 번호')),
                ('correct_answer', models.IntegerField(verbose_name='정답')),
                ('score', models.IntegerField(default=2, verbose_name='배점')),
                ('category', models.CharField(choices=[('LISTENING', '듣기'), ('VOCAB', '어휘'), ('GRAMMAR', '어법'), ('READING', '독해')], default='READING', max_length=10, verbose_name='유형')),
                ('mock_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mock.mockexaminfo')),
            ],
            options={
                'verbose_name': '문항 정답',
                'verbose_name_plural': '문항 정답',
                'ordering': ['number'],
                'unique_together': {('mock_exam', 'number')},
            },
        ),
    ]
