# Generated by Django 6.0 on 2026-01-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0002_mockexaminfo_mockexamquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockexamquestion',
            name='category',
            field=models.CharField(choices=[('LISTENING', '듣기'), ('PURPOSE', '목적/심경'), ('TOPIC', '주제/제목/요지/주장'), ('DATA', '도표/안내문/일치'), ('MEANING', '함축의미추론'), ('GRAMMAR', '어법'), ('VOCAB', '어휘'), ('BLANK', '빈칸추론'), ('FLOW', '무관한 문장'), ('ORDER', '글의 순서'), ('INSERT', '문장 삽입'), ('SUMMARY', '요약문'), ('LONG', '장문독해')], default='TOPIC', max_length=20, verbose_name='유형'),
        ),
    ]
