# Generated by Django 6.0 on 2026-01-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0003_alter_mockexamquestion_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockexam',
            name='student_answers',
            field=models.JSONField(default=dict, verbose_name='학생 마킹 답안'),
        ),
        migrations.AddField(
            model_name='mockexam',
            name='wrong_question_numbers',
            field=models.JSONField(default=list, verbose_name='틀린 문항 번호'),
        ),
    ]
