# Generated by Django 6.0 on 2025-12-31 21:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('vocab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='교재명')),
                ('publisher', models.CharField(blank=True, max_length=50, verbose_name='출판사')),
                ('level', models.CharField(blank=True, max_length=20, verbose_name='레벨')),
                ('category', models.CharField(choices=[('SYNTAX', '📘 구문 교재'), ('READING', '📙 독해 교재'), ('GRAMMAR', '📗 어법 교재')], default='SYNTAX', max_length=10, verbose_name='교재 유형')),
                ('total_units', models.IntegerField(default=0, verbose_name='총 챕터/강 수 (그래프용)')),
            ],
            options={
                'verbose_name': '교재',
                'verbose_name_plural': '교재',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ClassLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('SYNTAX', '구문'), ('READING', '독해'), ('GRAMMAR', '어법')], default='SYNTAX', max_length=20, verbose_name='과목')),
                ('date', models.DateField(verbose_name='수업 날짜')),
                ('comment', models.TextField(blank=True, verbose_name='선생님 코멘트')),
                ('next_hw_start', models.IntegerField(blank=True, null=True, verbose_name='다음 과제 시작 강')),
                ('next_hw_end', models.IntegerField(blank=True, null=True, verbose_name='다음 과제 끝 강')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='선생님 코멘트 (과제용)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hw_vocab_range', models.CharField(blank=True, max_length=50, verbose_name='과제 단어 범위')),
                ('hw_main_range', models.CharField(blank=True, max_length=50, verbose_name='과제 진도 범위')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='알림 발송 시간')),
                ('hw_vocab_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hw_logs', to='vocab.wordbook', verbose_name='과제 단어장')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_logs', to='core.studentprofile', verbose_name='학생')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_logs', to=settings.AUTH_USER_MODEL)),
                ('hw_main_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hw_logs', to='academy.textbook', verbose_name='과제 주교재')),
            ],
            options={
                'verbose_name': '수업 일지',
                'verbose_name_plural': '수업 일지',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TemporarySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('SYNTAX', '구문'), ('READING', '독해'), ('GRAMMAR', '어법')], default='SYNTAX', max_length=10, verbose_name='보강 과목')),
                ('is_extra_class', models.BooleanField(default=False, help_text="체크하면 '기존 수업일(Original Date)'을 입력하지 않아도 됩니다.", verbose_name='추가 보충 여부')),
                ('original_date', models.DateField(blank=True, null=True, verbose_name='기존 수업일 (결석/변경 시)')),
                ('new_date', models.DateField(verbose_name='보강/변경 날짜')),
                ('new_start_time', models.TimeField(blank=True, null=True, verbose_name='시작 시간')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='사유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_schedules', to='core.studentprofile', verbose_name='학생')),
                ('target_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classtime', verbose_name='기존 시간표에서 선택')),
            ],
            options={
                'verbose_name': '보강 및 일정 변경',
                'verbose_name_plural': '보강 및 일정 변경',
            },
        ),
        migrations.CreateModel(
            name='ClassLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_range', models.CharField(max_length=20, verbose_name='진도 범위(숫자)')),
                ('score', models.CharField(blank=True, max_length=10, null=True, verbose_name='성취도/점수')),
                ('class_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='academy.classlog')),
                ('wordbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocab.wordbook', verbose_name='단어장')),
                ('textbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.textbook', verbose_name='교재')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='날짜')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='등원 시간')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='하원 시간')),
                ('status', models.CharField(choices=[('PRESENT', '✅ 출석'), ('LATE', '⚠️ 지각'), ('ABSENT', '❌ 결석')], default='PRESENT', max_length=10, verbose_name='상태')),
                ('message_sent', models.BooleanField(default=False, verbose_name='알림 발송 여부')),
                ('memo', models.CharField(blank=True, max_length=50, verbose_name='비고')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.studentprofile', verbose_name='학생')),
            ],
            options={
                'verbose_name': '일일 출석부',
                'verbose_name_plural': '일일 출석부',
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TextbookUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField(verbose_name='강 번호')),
                ('link_url', models.URLField(blank=True, verbose_name='링크 URL')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='academy.textbook', verbose_name='교재')),
            ],
            options={
                'verbose_name': '교재 단원',
                'verbose_name_plural': '교재 단원',
                'ordering': ['textbook', 'unit_number'],
                'unique_together': {('textbook', 'unit_number')},
            },
        ),
    ]
