# Generated by Django 6.0 on 2026-01-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlog',
            name='reading_test_score',
            field=models.CharField(blank=True, help_text='예: 통과, 재시, 80점', max_length=20, verbose_name='독해 테스트 결과'),
        ),
        migrations.AddField(
            model_name='classlog',
            name='reading_test_type',
            field=models.CharField(blank=True, help_text='예: 빈칸추론, 순서배열', max_length=50, verbose_name='독해 테스트 유형'),
        ),
    ]
