# Generated by Django 6.0 on 2026-01-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_classlog_reading_test_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='category',
            field=models.CharField(choices=[('SYNTAX', '📘 구문 교재'), ('READING', '📙 독해 교재'), ('GRAMMAR', '📗 어법 교재'), ('SCHOOL_EXAM', '🏫 내신 대비')], default='SYNTAX', max_length=12, verbose_name='교재 유형'),
        ),
    ]
